// Generated by sync-ontology.ts
// Do not edit this file directly.
import { TargetCompany } from './target-company';

export interface Deal {
  id: string;
  targets: TargetCompany[];
  has_process_type: string[];
  deal_similarity: Deal[];
} 