// Generated by sync-ontology.ts
// Do not edit this file directly.
import { Deal } from './deal';
import { Fund } from './fund';
import { Sponsor } from './sponsor';
import { TargetCompany } from './target-company';

export interface Investor {
  id: string;
  invested_in: Deal[];
  manages: Fund[];
  bid_on: Deal[];
  has_relationship_with: (Sponsor | TargetCompany)[];
  exited: Deal[];
} 