version: '3.8'

services:
  neo4j:
    image: neo4j:5-community
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_PLUGINS: '["apoc", "graph-data-science", "neosemantics"]'
      NEO4J_dbms_security_procedures_unrestricted: apoc.*,n10s.*
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins

  neo4j-test:
    image: neo4j:5-community
    ports:
      - "7475:7474"  # HTTP
      - "7688:7687"  # Bolt
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_PLUGINS: '["apoc", "neosemantics"]'
      NEO4J_dbms_security_procedures_unrestricted: apoc.*,n10s.*
    volumes:
      - neo4j_test_data:/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  nlp-service:
    build:
      context: ./python-services/nlp-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # NLP Service API
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ENABLE_PROMPT_DEBUG=${ENABLE_PROMPT_DEBUG:-0}
    volumes:
      - nlp_cache:/app/cache
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
  neo4j_test_data:
  redis_data:
  nlp_cache: 