// Generated by sync-ontology.ts
// Do not edit this file directly.

import { FIBOTransactionType } from '../entities/fibo-transaction-type';

export interface IFIBOTransactionTypeRepository {
  findById(id: string): Promise<FIBOTransactionType | null>;
  save(entity: FIBOTransactionType): Promise<void>;
  // Additional repository methods will be added as needed
} 