// Generated by sync-ontology.ts
// Do not edit this file directly.

import { FIBOMarketDataType } from '../entities/fibo-market-data-type';

export interface IFIBOMarketDataTypeRepository {
  findById(id: string): Promise<FIBOMarketDataType | null>;
  save(entity: FIBOMarketDataType): Promise<void>;
  // TODO: Add other repository methods
} 