// Generated by sync-ontology.ts
// Do not edit this file directly.

import { DealDTO } from '@generated/financial/generated/DealDTO';

export interface IDealRepository {
  findById(id: string): Promise<DealDTO | null>;
  save(entity: DealDTO): Promise<DealDTO>;
  // Additional repository methods will be added as needed
} 