// Generated by sync-ontology.ts
// Do not edit this file directly.

import { InvestorDTO } from '@generated/financial/InvestorDTO';

export interface IInvestorRepository {
  findById(id: string): Promise<InvestorDTO | null>;
  save(entity: InvestorDTO): Promise<InvestorDTO>;
  // Additional repository methods will be added as needed
} 