// Generated by sync-ontology.ts
// Do not edit this file directly.

import { Relationship } from '../entities/relationship';

export interface IRelationshipRepository {
  findById(id: string): Promise<Relationship | null>;
  save(entity: Relationship): Promise<void>;
  // Additional repository methods will be added as needed
} 