// Generated by sync-ontology.ts
// Do not edit this file directly.

export interface ActivityType {
  id: string;
  Identify: string;
  Attract: string;
  Acquire: string;
  Develop: string;
  Retain: string;
  LeadQualification: string;
  OpportunityManagement: string;
  ProposalPreparation: string;
  Negotiation: string;
  Closing: string;
  CampaignExecution: string;
  ContentCreation: string;
  MarketResearch: string;
  BrandManagement: string;
  CustomerSupport: string;
  IssueResolution: string;
  Maintenance: string;
  Training: string;
  DataCollection: string;
  DataAnalysis: string;
  Reporting: string;
  DocumentManagement: string;
} 