// Generated by sync-ontology.ts
// Do not edit this file directly.

export interface DOLCECategory {
  id: string;
  Endurant: string;
  Perdurant: string;
  Quality: string;
  Abstract: string;
  AgentivePhysicalObject: string;
  NonAgentivePhysicalObject: string;
} 