// Generated by sync-ontology.ts
// Do not edit this file directly.

export interface KnowledgeType {
  id: string;
  CustomerProfile: string;
  CustomerPreferences: string;
  CustomerBehavior: string;
  CustomerHistory: string;
  MarketIntelligence: string;
  CompetitiveAnalysis: string;
  ProductKnowledge: string;
  ProcessKnowledge: string;
  TransactionData: string;
  InteractionHistory: string;
  CommunicationLog: string;
} 