// Generated by sync-ontology.ts
// Do not edit this file directly.

export interface SoftwareType {
  id: string;
  CRMPlatform: string;
  SalesAutomation: string;
  MarketingAutomation: string;
  EmailSystem: string;
  KnowledgeGraph: string;
  API: string;
} 