// Generated by sync-ontology.ts
// Do not edit this file directly.

import { Deal } from '../entities/deal';

export interface IDealRepository {
  findById(id: string): Promise<Deal | null>;
  save(entity: Deal): Promise<void>;
  // TODO: Add other repository methods
} 