// Generated by sync-ontology.ts
// Do not edit this file directly.

import { Fund } from '../entities/fund';

export interface IFundRepository {
  findById(id: string): Promise<Fund | null>;
  save(entity: Fund): Promise<void>;
  // TODO: Add other repository methods
} 