// Generated by sync-ontology.ts
// Do not edit this file directly.

import { Sponsor } from '../entities/sponsor';

export interface ISponsorRepository {
  findById(id: string): Promise<Sponsor | null>;
  save(entity: Sponsor): Promise<void>;
  // TODO: Add other repository methods
} 