// Generated by sync-ontology.ts
// Do not edit this file directly.

import { DOLCECategory } from '../entities/dolce-category';

export interface IDOLCECategoryRepository {
  findById(id: string): Promise<DOLCECategory | null>;
  save(entity: DOLCECategory): Promise<void>;
  // Additional repository methods will be added as needed
} 