// Generated by sync-ontology.ts
// Do not edit this file directly.

import { ActivityType } from '../entities/activity-type';

export interface IActivityTypeRepository {
  findById(id: string): Promise<ActivityType | null>;
  save(entity: ActivityType): Promise<void>;
  // TODO: Add other repository methods
} 