// Generated by sync-ontology.ts
// Do not edit this file directly.

import { KnowledgeType } from '../entities/knowledge-type';

export interface IKnowledgeTypeRepository {
  findById(id: string): Promise<KnowledgeType | null>;
  save(entity: KnowledgeType): Promise<void>;
  // Additional repository methods will be added as needed
} 