// Generated by sync-ontology.ts
// Do not edit this file directly.

import { RelationshipType } from '../entities/relationship-type';

export interface IRelationshipTypeRepository {
  findById(id: string): Promise<RelationshipType | null>;
  save(entity: RelationshipType): Promise<void>;
  // Additional repository methods will be added as needed
} 