// Generated by sync-ontology.ts
// Do not edit this file directly.

import { SoftwareType } from '../entities/software-type';

export interface ISoftwareTypeRepository {
  findById(id: string): Promise<SoftwareType | null>;
  save(entity: SoftwareType): Promise<void>;
  // Additional repository methods will be added as needed
} 