// Generated by sync-ontology.ts
// Do not edit this file directly.

import { FIBOInstitutionType } from '../entities/fibo-institution-type';

export interface IFIBOInstitutionTypeRepository {
  findById(id: string): Promise<FIBOInstitutionType | null>;
  save(entity: FIBOInstitutionType): Promise<void>;
  // TODO: Add other repository methods
} 