// Generated by sync-ontology.ts
// Do not edit this file directly.

import { GeographicRegion } from '../entities/geographic-region';

export interface IGeographicRegionRepository {
  findById(id: string): Promise<GeographicRegion | null>;
  save(entity: GeographicRegion): Promise<void>;
  // TODO: Add other repository methods
} 