// Generated by sync-ontology.ts
// Do not edit this file directly.

import { Investor } from '../entities/investor';

export interface IInvestorRepository {
  findById(id: string): Promise<Investor | null>;
  save(entity: Investor): Promise<void>;
  // TODO: Add other repository methods
} 