// Generated by sync-ontology.ts
// Do not edit this file directly.

import { Mandate } from '../entities/mandate';

export interface IMandateRepository {
  findById(id: string): Promise<Mandate | null>;
  save(entity: Mandate): Promise<void>;
  // Additional repository methods will be added as needed
} 