// Generated by sync-ontology.ts
// Do not edit this file directly.

import { Sector } from '../entities/sector';

export interface ISectorRepository {
  findById(id: string): Promise<Sector | null>;
  save(entity: Sector): Promise<void>;
  // Additional repository methods will be added as needed
} 