// Generated by sync-ontology.ts
// Do not edit this file directly.

import { TargetCompany } from '../entities/target-company';

export interface ITargetCompanyRepository {
  findById(id: string): Promise<TargetCompany | null>;
  save(entity: TargetCompany): Promise<void>;
  // Additional repository methods will be added as needed
} 