// Generated by sync-ontology.ts
// Do not edit this file directly.
import { Deal } from '.';
import { TargetCompany } from '.';
import { Deal } from '.';

export interface Deal {
  id: string;
  targets: TargetCompany[];
  has_process_type: string[];
  similar_to: Deal[];
} 