// Generated by sync-ontology.ts
// Do not edit this file directly.
import { Investor } from '.';
import { Deal } from '.';
import { Fund } from '.';
import { Sponsor } from '.';
import { TargetCompany } from '.';

export interface Investor {
  id: string;
  invested_in: Deal[];
  manages: Fund[];
  bid_on: Deal[];
  has_relationship_with: (Sponsor | TargetCompany)[];
  exited: Deal[];
} 