// Generated by sync-ontology.ts
// Do not edit this file directly.
import { Sector } from './sector';
import { GeographicRegion } from './geographic-region';

export interface TargetCompany {
  id: string;
  operates_in: (Sector | GeographicRegion)[];
} 