// Generated by sync-ontology.ts
// Do not edit this file directly.
import { TargetCompany } from '.';
import { Sector } from '.';
import { GeographicRegion } from '.';

export interface TargetCompany {
  id: string;
  operates_in: (Sector | GeographicRegion)[];
} 