// Generated by sync-ontology.ts
// Do not edit this file directly.

export interface FIBOInstrumentType {
  id: string;
  EQUITY: string;
  BOND: string;
  DERIVATIVE: string;
  CURRENCY: string;
  COMMODITY: string;
  FUND: string;
} 