// Generated by sync-ontology.ts
// Do not edit this file directly.

export interface FIBOInstitutionType {
  id: string;
  BANK: string;
  INVESTMENT_FIRM: string;
  INSURANCE_COMPANY: string;
  PENSION_FUND: string;
  HEDGE_FUND: string;
  MUTUAL_FUND: string;
} 