// Generated by sync-ontology.ts
// Do not edit this file directly.

export interface FIBOTransactionType {
  id: string;
  BUY: string;
  SELL: string;
  TRANSFER: string;
  DERIVATIVE_TRADE: string;
  CURRENCY_EXCHANGE: string;
  PAYMENT: string;
} 