// Generated by sync-ontology.ts
// Do not edit this file directly.

export interface RelationshipType {
  id: string;
  CustomerRelationship: string;
  SupplierRelationship: string;
  PartnerRelationship: string;
  ProspectRelationship: string;
  Employment: string;
  Collaboration: string;
  Membership: string;
  Before: string;
  After: string;
  During: string;
  Overlaps: string;
} 