// Generated by sync-ontology.ts
// Do not edit this file directly.

export interface FIBOMarketDataType {
  id: string;
  PRICE: string;
  VOLUME: string;
  BID: string;
  ASK: string;
  SPREAD: string;
  VOLATILITY: string;
} 