// Generated by sync-ontology.ts
// Do not edit this file directly.

import { FIBOInstrumentType } from '../entities/fibo-instrument-type';

export interface IFIBOInstrumentTypeRepository {
  findById(id: string): Promise<FIBOInstrumentType | null>;
  save(entity: FIBOInstrumentType): Promise<void>;
  // Additional repository methods will be added as needed
} 